In [3]:
import pandas as pd 
import numpy as n
import seaborn as s
import matplotlib.pyplot as pl

In [4]:
c= pd.read_csv("C:/Users/akrit/Downloads/Book1.csv")

In [5]:
c

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,692-92-5582,B,Mandalay,Member,Female,Food_and_beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9
1,351-62-0822,B,Mandalay,Member,Female,Fashion_accessories,14.48,4,2.8960,60.8160,02-06-2019,18:07,Ewallet,57.92,4.761905,2.8960,4.5
2,529-56-3974,B,Mandalay,Member,Male,Electronic_accessories,25.51,4,5.1020,107.1420,03-09-2019,17:03,Cash,102.04,4.761905,5.1020,6.8
3,299-46-1805,B,Mandalay,Member,Female,Sports_and_travel,93.72,6,28.1160,590.4360,1/15/2019,16:19,Cash,562.32,4.761905,28.1160,4.5
4,319-50-3348,B,Mandalay,Normal,Female,Home_and_lifestyle,40.30,2,4.0300,84.6300,03-11-2019,15:30,Ewallet,80.60,4.761905,4.0300,4.4
5,371-85-5789,B,Mandalay,Normal,Male,Health_and_beauty,87.98,3,13.1970,277.1370,03-05-2019,10:40,Ewallet,263.94,4.761905,13.1970,5.1
6,273-16-6619,B,Mandalay,Normal,Male,Home_and_lifestyle,33.20,2,3.3200,69.7200,3/15/2019,12:20,Credit card,66.40,4.761905,3.3200,4.4
7,649-29-6775,B,Mandalay,Normal,Male,Fashion_accessories,33.52,1,1.6760,35.1960,02-08-2019,15:31,Cash,33.52,4.761905,1.6760,6.7
8,145-94-9061,B,Mandalay,Normal,Female,Food_and_beverages,88.36,5,22.0900,463.8900,1/25/2019,19:48,Cash,441.80,4.761905,22.0900,9.6
9,871-79-8483,B,Mandalay,Normal,Male,Fashion_accessories,94.13,5,23.5325,494.1825,2/25/2019,19:39,Credit card,470.65,4.761905,23.5325,4.8
10,149-71-6266,B,Mandalay,Member,Male,Sports_and_travel,78.07,9,35.1315,737.7615,1/28/2019,12:43,Cash,702.63,4.761905,35.1315,4.5
11,640-49-2076,B,Mandalay,Normal,Male,Sports_and_travel,83.78,8,33.5120,703.7520,01-10-2019,14:49,Cash,670.24,4.761905,33.5120,5.1
12,777-82-7220,B,Mandalay,Member,Male,Home_and_lifestyle,30.12,8,12.0480,253.0080,03-03-2019,13:01,Cash,240.96,4.761905,12.0480,7.7
13,280-35-5823,B,Mandalay,Member,Female,Home_and_lifestyle,86.72,1,4.3360,91.0560,1/17/2019,18:45,Ewallet,86.72,4.761905,4.3360,7.9
14,354-25-5821,B,Mandalay,Member,Female,Sports_and_travel,69.12,6,20.7360,435.4560,02-08-2019,13:03,Cash,414.72,4.761905,20.7360,5.6
15,132-32-9879,B,Mandalay,Member,Female,Electronic_accessories,93.96,4,18.7920,394.6320,03-09-2019,18:00,Cash,375.84,4.761905,18.7920,9.5
16,370-41-7321,B,Mandalay,Member,Male,Health_and_beauty,56.69,9,25.5105,535.7205,2/27/2019,17:24,Credit card,510.21,4.761905,25.5105,8.4
17,727-46-3608,B,Mandalay,Member,Female,Food_and_beverages,20.01,9,9.0045,189.0945,02-06-2019,15:47,Ewallet,180.09,4.761905,9.0045,4.1
18,669-54-1719,B,Mandalay,Member,Male,Electronic_accessories,18.93,6,5.6790,119.2590,02-10-2019,12:45,Credit card,113.58,4.761905,5.6790,8.1
19,616-24-2851,B,Mandalay,Member,Female,Fashion_accessories,17.87,4,3.5740,75.0540,3/22/2019,14:42,Ewallet,71.48,4.761905,3.5740,6.5
20,242-55-6721,B,Mandalay,Normal,Male,Home_and_lifestyle,16.16,2,1.6160,33.9360,03-07-2019,11:49,Ewallet,32.32,4.761905,1.6160,6.5
21,347-34-2234,B,Mandalay,Member,Female,Sports_and_travel,55.07,9,24.7815,520.4115,02-03-2019,13:40,Ewallet,495.63,4.761905,24.7815,10.0
22,853-23-2453,B,Mandalay,Member,Male,Health_and_beauty,75.74,4,15.1480,318.1080,2/14/2019,14:35,Cash,302.96,4.761905,15.1480,7.6
23,109-28-2512,B,Mandalay,Member,Female,Fashion_accessories,97.61,6,29.2830,614.9430,01-07-2019,15:01,Ewallet,585.66,4.761905,29.2830,9.9
24,510-95-6347,B,Mandalay,Member,Female,Food_and_beverages,48.52,3,7.2780,152.8380,03-05-2019,18:17,Ewallet,145.56,4.761905,7.2780,4.0
25,847-38-7188,B,Mandalay,Normal,Female,Food_and_beverages,96.68,3,14.5020,304.5420,1/26/2019,19:56,Ewallet,290.04,4.761905,14.5020,6.4
26,318-68-5053,B,Mandalay,Normal,Female,Health_and_beauty,76.99,6,23.0970,485.0370,2/27/2019,17:55,Cash,461.94,4.761905,23.0970,6.1
27,152-08-9985,B,Mandalay,Member,Male,Health_and_beauty,64.36,9,28.9620,608.2020,03-12-2019,12:09,Credit card,579.24,4.761905,28.9620,8.6
28,766-85-7061,B,Mandalay,Normal,Male,Health_and_beauty,87.87,10,43.9350,922.6350,3/29/2019,10:25,Ewallet,878.70,4.761905,43.9350,5.1
29,733-01-9107,B,Mandalay,Normal,Male,Home_and_lifestyle,82.70,6,24.8100,521.0100,03-05-2019,18:14,Cash,496.20,4.761905,24.8100,7.4
30,716-39-1409,B,Mandalay,Normal,Male,Health_and_beauty,30.35,7,10.6225,223.0725,3/19/2019,18:19,Cash,212.45,4.761905,10.6225,8.0
31,479-26-8945,B,Mandalay,Member,Female,Sports_and_travel,16.49,2,1.6490,34.6290,02-05-2019,11:32,Ewallet,32.98,4.761905,1.6490,4.6
32,227-78-1148,B,Mandalay,Normal,Female,Fashion_accessories,72.84,7,25.4940,535.3740,2/15/2019,12:44,Cash,509.88,4.761905,25.4940,8.4
33,291-32-1427,B,Mandalay,Member,Male,Fashion_accessories,21.94,5,5.4850,115.1850,03-05-2019,12:29,Ewallet,109.70,4.761905,5.4850,5.3
34,659-65-8956,B,Mandalay,Member,Male,Fashion_accessories,51.36,1,2.5680,53.9280,1/16/2019,15:26,Ewallet,51.36,4.761905,2.5680,5.2
35,378-24-2715,B,Mandalay,Normal,Male,Home_and_lifestyle,53.44,2,5.3440,112.2240,1/20/2019,20:38,Ewallet,106.88,4.761905,5.3440,4.1
36,219-22-9386,B,Mandalay,Member,Male,Sports_and_travel,99.96,9,44.9820,944.6220,03-09-2019,17:26,Credit card,899.64,4.761905,44.9820,4.2
37,268-27-6179,B,Mandalay,Member,Female,Fashion_accessories,56.47,8,22.5880,474.3480,03-09-2019,14:57,Ewallet,451.76,4.761905,22.5880,7.3
38,549-84-7482,B,Mandalay,Normal,Female,Sports_and_travel,90.28,9,40.6260,853.1460,02-08-2019,11:15,Ewallet,812.52,4.761905,40.6260,7.2
39,191-10-6171,B,Mandalay,Normal,Female,Fashion_accessories,39.62,7,13.8670,291.2070,1/25/2019,13:18,Cash,277.34,4.761905,13.8670,7.5
40,695-51-0018,B,Mandalay,Normal,Female,Sports_and_travel,34.84,4,6.9680,146.3280,02-10-2019,18:36,Cash,139.36,4.761905,6.9680,7.4
41,590-83-4591,B,Mandalay,Member,Male,Electronic_accessories,87.45,6,26.2350,550.9350,2/17/2019,14:40,Credit card,524.70,4.761905,26.2350,8.8
42,241-72-9525,B,Mandalay,Normal,Male,Sports_and_travel,51.91,10,25.9550,545.0550,2/16/2019,12:21,Cash,519.10,4.761905,25.9550,8.2
43,262-47-2794,B,Mandalay,Member,Male,Home_and_lifestyle,71.86,8,28.7440,603.6240,03-06-2019,15:07,Credit card,574.88,4.761905,28.7440,6.2
44,608-96-3517,B,Mandalay,Member,Female,Fashion_accessories,91.54,4,18.3080,384.4680,3/23/2019,19:20,Credit card,366.16,4.761905,18.3080,4.8
45,279-74-2924,B,Mandalay,Member,Male,Electronic_accessories,72.17,1,3.6085,75.7785,01-04-2019,19:40,Cash,72.17,4.761905,3.6085,6.1
46,307-85-2293,B,Mandalay,Normal,Male,Home_and_lifestyle,50.28,5,12.5700,263.9700,03-07-2019,13:58,Ewallet,251.40,4.761905,12.5700,9.7
47,743-04-1105,B,Mandalay,Member,Male,Health_and_beauty,97.22,9,43.7490,918.7290,3/30/2019,14:43,Ewallet,874.98,4.761905,43.7490,6.0
48,423-57-2993,B,Mandalay,Normal,Male,Sports_and_travel,93.39,6,28.0170,588.3570,3/27/2019,19:18,Ewallet,560.34,4.761905,28.0170,10.0
49,548-46-9322,B,Mandalay,Normal,Male,Food_and_beverages,39.90,10,19.9500,418.9500,2/20/2019,15:24,Credit card,399.00,4.761905,19.9500,5.9
50,505-02-0892,B,Mandalay,Member,Male,Health_and_beauty,42.57,8,17.0280,357.5880,2/25/2019,14:12,Ewallet,340.56,4.761905,17.0280,5.6

In [6]:
c.shape

(51, 17)

In [7]:
c.head(30)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,692-92-5582,B,Mandalay,Member,Female,Food_and_beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9
1,351-62-0822,B,Mandalay,Member,Female,Fashion_accessories,14.48,4,2.8960,60.8160,02-06-2019,18:07,Ewallet,57.92,4.761905,2.8960,4.5
2,529-56-3974,B,Mandalay,Member,Male,Electronic_accessories,25.51,4,5.1020,107.1420,03-09-2019,17:03,Cash,102.04,4.761905,5.1020,6.8
3,299-46-1805,B,Mandalay,Member,Female,Sports_and_travel,93.72,6,28.1160,590.4360,1/15/2019,16:19,Cash,562.32,4.761905,28.1160,4.5
4,319-50-3348,B,Mandalay,Normal,Female,Home_and_lifestyle,40.30,2,4.0300,84.6300,03-11-2019,15:30,Ewallet,80.60,4.761905,4.0300,4.4
5,371-85-5789,B,Mandalay,Normal,Male,Health_and_beauty,87.98,3,13.1970,277.1370,03-05-2019,10:40,Ewallet,263.94,4.761905,13.1970,5.1
6,273-16-6619,B,Mandalay,Normal,Male,Home_and_lifestyle,33.20,2,3.3200,69.7200,3/15/2019,12:20,Credit card,66.40,4.761905,3.3200,4.4
7,649-29-6775,B,Mandalay,Normal,Male,Fashion_accessories,33.52,1,1.6760,35.1960,02-08-2019,15:31,Cash,33.52,4.761905,1.6760,6.7
8,145-94-9061,B,Mandalay,Normal,Female,Food_and_beverages,88.36,5,22.0900,463.8900,1/25/2019,19:48,Cash,441.80,4.761905,22.0900,9.6
9,871-79-8483,B,Mandalay,Normal,Male,Fashion_accessories,94.13,5,23.5325,494.1825,2/25/2019,19:39,Credit card,470.65,4.761905,23.5325,4.8
10,149-71-6266,B,Mandalay,Member,Male,Sports_and_travel,78.07,9,35.1315,737.7615,1/28/2019,12:43,Cash,702.63,4.761905,35.1315,4.5
11,640-49-2076,B,Mandalay,Normal,Male,Sports_and_travel,83.78,8,33.5120,703.7520,01-10-2019,14:49,Cash,670.24,4.761905,33.5120,5.1
12,777-82-7220,B,Mandalay,Member,Male,Home_and_lifestyle,30.12,8,12.0480,253.0080,03-03-2019,13:01,Cash,240.96,4.761905,12.0480,7.7
13,280-35-5823,B,Mandalay,Member,Female,Home_and_lifestyle,86.72,1,4.3360,91.0560,1/17/2019,18:45,Ewallet,86.72,4.761905,4.3360,7.9
14,354-25-5821,B,Mandalay,Member,Female,Sports_and_travel,69.12,6,20.7360,435.4560,02-08-2019,13:03,Cash,414.72,4.761905,20.7360,5.6
15,132-32-9879,B,Mandalay,Member,Female,Electronic_accessories,93.96,4,18.7920,394.6320,03-09-2019,18:00,Cash,375.84,4.761905,18.7920,9.5
16,370-41-7321,B,Mandalay,Member,Male,Health_and_beauty,56.69,9,25.5105,535.7205,2/27/2019,17:24,Credit card,510.21,4.761905,25.5105,8.4
17,727-46-3608,B,Mandalay,Member,Female,Food_and_beverages,20.01,9,9.0045,189.0945,02-06-2019,15:47,Ewallet,180.09,4.761905,9.0045,4.1
18,669-54-1719,B,Mandalay,Member,Male,Electronic_accessories,18.93,6,5.6790,119.2590,02-10-2019,12:45,Credit card,113.58,4.761905,5.6790,8.1
19,616-24-2851,B,Mandalay,Member,Female,Fashion_accessories,17.87,4,3.5740,75.0540,3/22/2019,14:42,Ewallet,71.48,4.761905,3.5740,6.5
20,242-55-6721,B,Mandalay,Normal,Male,Home_and_lifestyle,16.16,2,1.6160,33.9360,03-07-2019,11:49,Ewallet,32.32,4.761905,1.6160,6.5
21,347-34-2234,B,Mandalay,Member,Female,Sports_and_travel,55.07,9,24.7815,520.4115,02-03-2019,13:40,Ewallet,495.63,4.761905,24.7815,10.0
22,853-23-2453,B,Mandalay,Member,Male,Health_and_beauty,75.74,4,15.1480,318.1080,2/14/2019,14:35,Cash,302.96,4.761905,15.1480,7.6
23,109-28-2512,B,Mandalay,Member,Female,Fashion_accessories,97.61,6,29.2830,614.9430,01-07-2019,15:01,Ewallet,585.66,4.761905,29.2830,9.9
24,510-95-6347,B,Mandalay,Member,Female,Food_and_beverages,48.52,3,7.2780,152.8380,03-05-2019,18:17,Ewallet,145.56,4.761905,7.2780,4.0
25,847-38-7188,B,Mandalay,Normal,Female,Food_and_beverages,96.68,3,14.5020,304.5420,1/26/2019,19:56,Ewallet,290.04,4.761905,14.5020,6.4
26,318-68-5053,B,Mandalay,Normal,Female,Health_and_beauty,76.99,6,23.0970,485.0370,2/27/2019,17:55,Cash,461.94,4.761905,23.0970,6.1
27,152-08-9985,B,Mandalay,Member,Male,Health_and_beauty,64.36,9,28.9620,608.2020,03-12-2019,12:09,Credit card,579.24,4.761905,28.9620,8.6
28,766-85-7061,B,Mandalay,Normal,Male,Health_and_beauty,87.87,10,43.9350,922.6350,3/29/2019,10:25,Ewallet,878.70,4.761905,43.9350,5.1
29,733-01-9107,B,Mandalay,Normal,Male,Home_and_lifestyle,82.70,6,24.8100,521.0100,03-05-2019,18:14,Cash,496.20,4.761905,24.8100,7.4

In [8]:
d =c.head(15)

In [9]:
d.to_csv("C:/Users/akrit/Downloads/mmmm.csv",index = False)

In [10]:
d

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,692-92-5582,B,Mandalay,Member,Female,Food_and_beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9
1,351-62-0822,B,Mandalay,Member,Female,Fashion_accessories,14.48,4,2.8960,60.8160,02-06-2019,18:07,Ewallet,57.92,4.761905,2.8960,4.5
2,529-56-3974,B,Mandalay,Member,Male,Electronic_accessories,25.51,4,5.1020,107.1420,03-09-2019,17:03,Cash,102.04,4.761905,5.1020,6.8
3,299-46-1805,B,Mandalay,Member,Female,Sports_and_travel,93.72,6,28.1160,590.4360,1/15/2019,16:19,Cash,562.32,4.761905,28.1160,4.5
4,319-50-3348,B,Mandalay,Normal,Female,Home_and_lifestyle,40.30,2,4.0300,84.6300,03-11-2019,15:30,Ewallet,80.60,4.761905,4.0300,4.4
5,371-85-5789,B,Mandalay,Normal,Male,Health_and_beauty,87.98,3,13.1970,277.1370,03-05-2019,10:40,Ewallet,263.94,4.761905,13.1970,5.1
6,273-16-6619,B,Mandalay,Normal,Male,Home_and_lifestyle,33.20,2,3.3200,69.7200,3/15/2019,12:20,Credit card,66.40,4.761905,3.3200,4.4
7,649-29-6775,B,Mandalay,Normal,Male,Fashion_accessories,33.52,1,1.6760,35.1960,02-08-2019,15:31,Cash,33.52,4.761905,1.6760,6.7
8,145-94-9061,B,Mandalay,Normal,Female,Food_and_beverages,88.36,5,22.0900,463.8900,1/25/2019,19:48,Cash,441.80,4.761905,22.0900,9.6
9,871-79-8483,B,Mandalay,Normal,Male,Fashion_accessories,94.13,5,23.5325,494.1825,2/25/2019,19:39,Credit card,470.65,4.761905,23.5325,4.8
10,149-71-6266,B,Mandalay,Member,Male,Sports_and_travel,78.07,9,35.1315,737.7615,1/28/2019,12:43,Cash,702.63,4.761905,35.1315,4.5
11,640-49-2076,B,Mandalay,Normal,Male,Sports_and_travel,83.78,8,33.5120,703.7520,01-10-2019,14:49,Cash,670.24,4.761905,33.5120,5.1
12,777-82-7220,B,Mandalay,Member,Male,Home_and_lifestyle,30.12,8,12.0480,253.0080,03-03-2019,13:01,Cash,240.96,4.761905,12.0480,7.7
13,280-35-5823,B,Mandalay,Member,Female,Home_and_lifestyle,86.72,1,4.3360,91.0560,1/17/2019,18:45,Ewallet,86.72,4.761905,4.3360,7.9
14,354-25-5821,B,Mandalay,Member,Female,Sports_and_travel,69.12,6,20.7360,435.4560,02-08-2019,13:03,Cash,414.72,4.761905,20.7360,5.6

In [11]:
d.shape

(15, 17)

In [12]:
ss =pd.read_excel("C:/Users/akrit/Downloads/supermarket_sales.xlsx",header=1)

In [13]:
ss

,692-92-5582,B,Mandalay,Member,Female,Food_and_beverages,54.84,3,8.226,172.746,2/20/2019,13:27:00,Credit card,164.52,4.761904762,8.226.1,5.9
0,351-62-0822,B,Mandalay,Member,Female,Fashion_accessories,14.48,4,2.896,60.816,2019-06-02 00:00:00,18:07:00,Ewallet,57.92,4.761905,2.896,4.5
1,529-56-3974,B,Mandalay,Member,Male,Electronic_accessories,25.51,4,5.102,107.142,2019-09-03 00:00:00,17:03:00,Cash,102.04,4.761905,5.102,6.8
2,299-46-1805,B,Mandalay,Member,Female,Sports_and_travel,93.72,6,28.116,590.436,1/15/2019,16:19:00,Cash,562.32,4.761905,28.116,4.5
3,319-50-3348,B,Mandalay,Normal,Female,Home_and_lifestyle,40.30,2,4.030,84.630,2019-11-03 00:00:00,15:30:00,Ewallet,80.60,4.761905,4.030,4.4
4,371-85-5789,B,Mandalay,Normal,Male,Health_and_beauty,87.98,3,13.197,277.137,2019-05-03 00:00:00,10:40:00,Ewallet,263.94,4.761905,13.197,5.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,886-18-2897,A,Yangon,Normal,Female,Food_and_beverages,56.56,5,14.140,296.940,3/22/2019,19:06:00,Credit card,282.80,4.761905,14.140,4.5
995,745-74-0715,A,Yangon,Normal,Male,Electronic_accessories,58.03,2,5.803,121.863,2019-10-03 00:00:00,20:46:00,Ewallet,116.06,4.761905,5.803,8.8
996,727-02-1313,A,Yangon,Member,Male,Food_and_beverages,31.84,1,1.592,33.432,2019-09-02 00:00:00,13:22:00,Cash,31.84,4.761905,1.592,7.7
997,347-56-2442,A,Yangon,Normal,Male,Home_and_lifestyle,65.82,1,3.291,69.111,2/22/2019,15:33:00,Cash,65.82,4.761905,3.291,4.1
998,849-09-3807,A,Yangon,Member,Female,Fashion_accessories,88.34,7,30.919,649.299,2/18/2019,13:28:00,Cash,618.38,4.761905,30.919,6.6

In [14]:
ss.shape

(999, 17)

In [15]:
sss =pd.read_csv("m.csv")

In [16]:
sss

    name      jj  marks
0  hello      as     60
1  mello      ss     90
2     he  ssasad     89

In [17]:
sss.shape

(3, 3)

In [18]:
f =pd.read_csv("C:/Users/akrit/Downloads/x.txt",engine= 'python',sep='-')

In [19]:
f

     name  marks  roll_number
0  akriti     99            4
1  rohini     89           10
2  sristi    100            9
3   rahul     66            7

In [20]:
emp_header =bb

NameError: name 'bb' is not defined

In [ ]:
emp_header

In [24]:
 df_prfx=pd.read_csv("C:/Users/akrit/Downloads/mmmm.csv")

In [25]:
tt = df_prfx.head(5)

In [26]:
tt

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,692-92-5582,B,Mandalay,Member,Female,Food_and_beverages,54.84,3,8.226,172.746,2/20/2019,13:27,Credit card,164.52,4.761905,8.226,5.9
1,351-62-0822,B,Mandalay,Member,Female,Fashion_accessories,14.48,4,2.896,60.816,02-06-2019,18:07,Ewallet,57.92,4.761905,2.896,4.5
2,529-56-3974,B,Mandalay,Member,Male,Electronic_accessories,25.51,4,5.102,107.142,03-09-2019,17:03,Cash,102.04,4.761905,5.102,6.8
3,299-46-1805,B,Mandalay,Member,Female,Sports_and_travel,93.72,6,28.116,590.436,1/15/2019,16:19,Cash,562.32,4.761905,28.116,4.5
4,319-50-3348,B,Mandalay,Normal,Female,Home_and_lifestyle,40.30,2,4.030,84.630,03-11-2019,15:30,Ewallet,80.60,4.761905,4.030,4.4

NameError: name 'tt' is not defined

##

tt.sort_values(by=[""])